title: Scott Merry's Blog
author: Scott Merry
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Scott Merry Blog GitHub

# social links
github_username:  scott-merry

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
